const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const app = fs.readFileSync(path.join(root, 'backend/src/App.tsx'), 'utf8')
const styles = fs.readFileSync(path.join(root, 'backend/src/styles.css'), 'utf8')

for (const value of ['shipping-required-packaging', 'shipping-required-sf-collect', 'shipping-required-notice', 'local-required-packaging', 'local-required-delivery-collect', 'local-required-notice', '包装泡沫冰袋', '默认顺丰特快到付', '同城外卖打包费', '同城配送费到付', '拍前必读']) assert.ok(app.includes(value), `missing fixed delivery product value: ${value}`)
assert.ok(app.includes("specId: 'standard'"), 'required products must use the standard spec')
assert.match(app, /required\?\.priceLocked \? 0 : Math\.round\(values\.deliveryPriceYuan \* 100\)/)
assert.match(app, /name: values\.name/)
assert.match(app, /category: required \? SHIPPING_REQUIRED_CATEGORY/)
assert.match(app, /supportsLocalDelivery: required\.methods\.includes\('local'\), supportsShipping: required\.methods\.includes\('shipping'\)/)
assert.match(app, /stockQuantity: required \? 999999 : values\.stockQuantity/)
assert.match(app, /stockQuantity: required \? 999999 : product\.stockQuantity/)
assert.ok(app.includes('disabled={Boolean(shippingRequiredConfig(r.productId))}'), 'required products must not expose sold-out/delete actions')
assert.ok(app.includes('disabled={item.name === SHIPPING_REQUIRED_CATEGORY}'), 'the fixed category must not expose deletion')
assert.ok(app.includes('固定规格：标准规格（specId=standard）'), 'required spec lock explanation must be visible')
assert.ok(app.includes('名称、图片、说明、排序以及打包商品的配送价格可维护'), 'required product name must remain editable')
assert.ok(!app.includes('shipping-required-panel'), 'required products must not render in a separate top panel')
assert.ok(!styles.includes('.shipping-required-grid'), 'obsolete required product panel styles must be removed')
assert.ok(app.includes('<Tag color="blue">配送必拍</Tag>'), 'required products should be marked in the normal product table')
assert.ok(app.includes('库存由系统保持充足，无需填写'), 'required product stock behavior must be explained')

console.log('backend shipping required product UI contract passed')
