const assert = require('assert')
const fs = require('fs')
const path = require('path')

const app = fs.readFileSync(path.join(__dirname, '..', 'backend', 'src', 'App.tsx'), 'utf8')
const css = fs.readFileSync(path.join(__dirname, '..', 'backend', 'src', 'styles.css'), 'utf8')

assert.ok(app.includes("order?.purchaseScene === 'pickup'"), 'pickup orders must also be printable')
assert.ok(app.includes("permissions.includes('orders.address.read')"), 'printing must require address permission')
assert.ok(app.includes('order.addressSnapshot'), 'printing must use the order address snapshot')
assert.ok(app.includes('address.contactName') && app.includes('address.phone') && app.includes('address.fullAddress'), 'printing must reject incomplete recipient data')
assert.ok(app.includes('window.print()'), 'printing must use the browser print dialog')
assert.ok(app.includes('商品小计') && app.includes('保温包装费') && app.includes('配送费') && app.includes('订单合计'), 'print sheet must include local delivery totals')
assert.ok(!app.includes('shippingIncludedItems') && app.includes('快递费用：默认顺丰特快到付'), 'shipping required products must stay in the normal item table and print must retain the collect-on-delivery notice')
assert.ok(!app.includes("adminApi.getAddress"), 'the backend must not fetch customer addresses separately')
assert.ok(css.includes('@media print') && css.includes('.order-print-sheet'), 'a dedicated print stylesheet is required')
assert.ok(app.includes('pageSize: 100') && app.includes('all.length < total'), 'CSV export must retrieve all filtered pages')
assert.ok(app.includes('DatePicker.RangePicker') && app.includes("orderStartDate: orderDateRange?.[0]?.format('YYYY-MM-DD')") && app.includes("orderEndDate: orderDateRange?.[1]?.format('YYYY-MM-DD')"), 'order date range must use stable YYYY-MM-DD listOrders fields')
assert.ok(app.includes('adminApi.listOrders({ ...filters, page, pageSize: 100 })'), 'CSV export must reuse the active order filters')
assert.ok(app.includes('\\ufeff') && app.includes("safe.replace(/\"/g, '\"\"')"), 'CSV must include BOM and escaping')
assert.ok(app.includes('/^\\s*[=+\\-@]/'), 'CSV cells must be protected from formula injection, including after whitespace')
assert.ok(app.includes('storeSnapshot?.name') && app.includes('storeSnapshot?.addressText'), 'pickup print must use the store snapshot')

console.log('backend order print UI contract passed')
