const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const merchant = fs.readFileSync(path.join(root, 'cloudfunctions/merchant-admin/index.js'), 'utf8')
const catalog = fs.readFileSync(path.join(root, 'cloudfunctions/catalog/index.js'), 'utf8')
const admin = fs.readFileSync(path.join(root, 'backend/src/App.tsx'), 'utf8')
const home = fs.readFileSync(path.join(root, 'miniprogram/pages/home/home.js'), 'utf8')
const homeTemplate = fs.readFileSync(path.join(root, 'miniprogram/pages/home/home.wxml'), 'utf8')

assert.match(merchant, /saveHomeRecommendations:\s*'products\.write'/)
assert.match(merchant, /productIds\.length > 6/)
assert.match(merchant, /homeRecommended:\s*recommended/)
assert.match(merchant, /products\.homeRecommendations\.write/)
assert.match(catalog, /action === 'listHomeRecommendations'/)
assert.match(catalog, /homeRecommended === true/)
assert.match(catalog, /homeRecommendOrder/)
assert.match(admin, /设置今日推荐/)
assert.match(admin, /saveHomeRecommendations\(recommendationIds\)/)
assert.match(home, /listHomeRecommendations\(\)/)
assert.match(homeTemplate, /wx:if="\{\{item\.primaryImageUrl\}\}"/)
assert.match(homeTemplate, /src="\{\{item\.primaryImageUrl\}\}"/)
assert.match(homeTemplate, /mode="aspectFill"/)

console.log('merchant home recommendations tests passed')
