const assert = require('assert')
const fs = require('fs')
const path = require('path')
const root = path.resolve(__dirname, '..')
const admin = fs.readFileSync(path.join(root, 'cloudfunctions/merchant-admin/index.js'), 'utf8')
const app = fs.readFileSync(path.join(root, 'backend/src/App.tsx'), 'utf8')
const api = fs.readFileSync(path.join(root, 'backend/src/admin-api.ts'), 'utf8')
assert(admin.includes('pageConfigurations'))
assert(admin.includes('uploadPageContentImage'))
assert(admin.includes('savePageConfiguration'))
assert(admin.includes('page-content/${event.pageId}/'))
assert(app.includes('adminApi.uploadPageContentImage'))
assert(!app.includes('localStorage.setItem(`page-content-${page}`'))
assert(api.includes('getPageConfiguration'))
assert(api.includes('savePageConfiguration'))
console.log('page-content cloud contract ok')
