const store = require('../../utils/store'), cart = require('../../utils/cart-service'), feeService = require('../../utils/fee-service'), productRepository = require('../../utils/product-repository')
const { hasRegularDeliveryItem } = require('../../utils/shipping-required-items')
Page({
  data: { items: [], method: 'local', address: null, subtotal: '¥0.00', insulation: '¥2.00', transport: '待填写地址后计算', total: '待填写地址后计算', transportLabel: '配送费', status: 'missingAddress', message: '待填写地址后计算', addressHint: '请先选择收货地址', empty: true, hasRegularItems: false, unavailableItems: [], unavailableMessage: '' },
  onShow() { const method = store.getState().deliveryMethod || 'local'; productRepository.list('delivery', method).then((result) => { store.setDeliveryMethod(method, result.items || []); this.sync() }).catch(() => this.sync()) },
  sync() { const state = store.getState(), items = store.getCart('delivery'), address = store.getSelectedAddress(), fee = feeService.calculateDeliveryFees({ deliveryMethod: state.deliveryMethod, address, items }), sub = cart.subtotal(items), unavailableItems = store.getUnavailableCartItems('delivery'); this.setData({ items: items.map((item) => Object.assign({}, item, { unitPrice: cart.money(item.unitPriceFen), unavailable: unavailableItems.some((current) => current.id === item.id) })), method: state.deliveryMethod, address, subtotal: cart.money(sub), insulation: cart.money(fee.insulationFeeFen), transport: state.deliveryMethod === 'shipping' ? '快递到付' : '配送费到付', total: fee.status === 'ready' ? cart.money(sub) : fee.message, transportLabel: fee.transportLabel, status: fee.status, message: fee.message, addressHint: address ? (fee.status === 'ready' ? '地址可配送' : fee.message) : '请先选择收货地址', empty: !items.length, hasRegularItems: hasRegularDeliveryItem(items), unavailableItems, unavailableMessage: unavailableItems.length ? '有商品已售罄或暂不支持当前配送方式，请切换方式或返回商品页调整。' : '' }) },
  change(e) { const item = this.data.items.find((entry) => entry.id === e.currentTarget.dataset.id); if (!item || item.shippingRequired) return; cart.setQuantity('delivery', item, Math.max(0, item.quantity + Number(e.currentTarget.dataset.delta))); this.sync() },
  method(e) { const method = e.currentTarget.dataset.method; productRepository.list('delivery', method).then((result) => { store.setDeliveryMethod(method, result.items || []); this.sync() }).catch(() => { store.setDeliveryMethod(method, []); this.sync() }) },
  checkout() { if (this.data.empty) return wx.showToast({ title: '购物车为空', icon: 'none' }); if (!this.data.hasRegularItems) return wx.showToast({ title: '请至少选择一件普通商品', icon: 'none' }); if (this.data.unavailableItems.length) return wx.showToast({ title: this.data.unavailableMessage, icon: 'none' }); if (this.data.status !== 'ready') return wx.showToast({ title: this.data.message, icon: 'none' }); wx.navigateTo({ url: '/pages/checkout/checkout' }) },
  address() { wx.navigateTo({ url: '/pages/addresses/addresses' }) }, back() { wx.navigateBack() }
})
