const stores = [
  { id: 'store-yuyuan', name: '愚园路店', address: '天山路 79 号', businessHours: '08:00—21:00', status: 'open', enabled: true, distanceText: '680m' },
  { id: 'store-jingan', name: '静安店', address: '常德路 220 号', businessHours: '09:00—20:00', status: 'closed', enabled: true, distanceText: '2.4km' }
]

const products = [
  { id: 'shipping-required-packaging', name: '包装泡沫冰袋', desc: '快递寄送保温防护', detailDesc: '用于快递寄送时的泡沫箱与冰袋包装，价格由商家维护。', priceFen: 0, deliveryPriceFen: 200, category: '拍前必读', artClass: 'art-milk', soldOut: false, enabled: true, supportsPickup: false, supportsLocalDelivery: false, supportsShipping: true, supportsLocal: false, specs: [{ id: 'standard', name: '标准规格', extraFeeFen: 0 }] },
  { id: 'shipping-required-sf-collect', name: '默认顺丰特快到付', desc: '快递费由收件人支付', detailDesc: '默认使用顺丰特快，快递费用到付，本商品价格固定为 0 元。', priceFen: 0, deliveryPriceFen: 0, category: '拍前必读', artClass: 'art-blue', soldOut: false, enabled: true, supportsPickup: false, supportsLocalDelivery: false, supportsShipping: true, supportsLocal: false, specs: [{ id: 'standard', name: '标准规格', extraFeeFen: 0 }] },
  { id: 'shipping-required-notice', name: '拍前必读', desc: '下单前请阅读快递说明', detailDesc: '请确认收件信息与快递到付规则，本商品价格固定为 0 元。', priceFen: 0, deliveryPriceFen: 0, category: '拍前必读', artClass: 'art-dark', soldOut: false, enabled: true, supportsPickup: false, supportsLocalDelivery: false, supportsShipping: true, supportsLocal: false, specs: [{ id: 'standard', name: '标准规格', extraFeeFen: 0 }] },
  { id: 'local-required-packaging', name: '同城外卖打包费', desc: '同城配送打包防护', detailDesc: '用于同城外卖的打包费用，价格由商家维护。', priceFen: 0, deliveryPriceFen: 200, category: '拍前必读', artClass: 'art-milk', soldOut: false, enabled: true, supportsPickup: false, supportsLocalDelivery: true, supportsShipping: false, supportsLocal: true, specs: [{ id: 'standard', name: '标准规格', extraFeeFen: 0 }] },
  { id: 'local-required-delivery-collect', name: '同城配送费到付', desc: '配送费用由收件人支付', detailDesc: '同城配送费用由收件人收货时支付，本商品价格固定为 0 元。', priceFen: 0, deliveryPriceFen: 0, category: '拍前必读', artClass: 'art-blue', soldOut: false, enabled: true, supportsPickup: false, supportsLocalDelivery: true, supportsShipping: false, supportsLocal: true, specs: [{ id: 'standard', name: '标准规格', extraFeeFen: 0 }] },
  { id: 'local-required-notice', name: '外卖拍前必读', desc: '下单前请阅读同城配送说明', detailDesc: '请确认收件信息与配送费到付规则，本商品价格固定为 0 元。', priceFen: 0, deliveryPriceFen: 0, category: '拍前必读', artClass: 'art-dark', soldOut: false, enabled: true, supportsPickup: false, supportsLocalDelivery: true, supportsShipping: false, supportsLocal: true, specs: [{ id: 'standard', name: '标准规格', extraFeeFen: 0 }] },
  { id: 'earl-grey', name: '伯爵茶可颂', desc: '黄油层层酥脆', detailDesc: '佛手柑的清香留在奶油里，27 层黄油面团烤出薄脆、轻盈的声响。', priceFen: 1680, deliveryPriceFen: 1880, category: '甜点', artClass: 'art-dark', soldOut: false, enabled: true, supportsPickup: true, supportsLocalDelivery: true, supportsShipping: true, supportsLocal: true, specs: [{ id: 'original', name: '原味', extraFeeFen: 0 }, { id: 'almond', name: '加杏仁片', extraFeeFen: 200 }] },
  { id: 'fig', name: '无花果酸面包', desc: '天然酵种慢发酵', detailDesc: '果干与天然酵种慢慢醒发，切开是柔软而丰盈的麦香。', priceFen: 2800, deliveryPriceFen: 3000, category: '欧包', artClass: 'art-milk', soldOut: false, enabled: true, supportsPickup: true, supportsLocalDelivery: true, supportsShipping: true, supportsLocal: true, specs: [{ id: 'sliced', name: '经典切片', extraFeeFen: 0 }, { id: 'whole', name: '整只装', extraFeeFen: 300 }] },
  { id: 'milk', name: '醇香牛乳吐司', desc: '云朵般柔软', detailDesc: '轻柔的牛乳香气和蓬松组织，适合带回家慢慢分享。', priceFen: 1980, deliveryPriceFen: 2180, category: '吐司', artClass: 'art-red', soldOut: false, enabled: true, supportsPickup: true, supportsLocalDelivery: true, supportsShipping: true, supportsLocal: true, specs: [{ id: 'standard', name: '标准规格', extraFeeFen: 0 }] },
  { id: 'coffee', name: '冷萃燕麦拿铁', desc: '清甜不腻', detailDesc: '顺滑燕麦奶遇上低温慢萃咖啡，清爽又有层次。', priceFen: 1400, deliveryPriceFen: 1600, category: '饮品', artClass: 'art-blue', soldOut: false, enabled: true, supportsPickup: true, supportsLocalDelivery: true, supportsShipping: true, supportsLocal: true, specs: [{ id: 'standard', name: '标准规格', extraFeeFen: 0 }] }
]

module.exports = { products, stores }
